# Generated by Django 5.2.7 on 2025-11-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('teks', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='quiz_images/')),
            ],
        ),
    ]
