# Generated by Django 5.2.7 on 2025-11-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materi',
            new_name='Quiz',
        ),
    ]
