# Generated by Django 5.2.7 on 2025-11-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_materi_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='gambar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
