# Generated by Django 5.2.7 on 2025-11-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='teks',
        ),
    ]
