# Generated by Django 5.2.7 on 2025-11-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_teks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
