# Generated by Django 5.2.7 on 2025-11-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('pilgan', 'Pilihan Ganda'), ('dragdrop', 'Drag & Drop'), ('isian', 'Isian'), ('benarsalah', 'Benar atau Salah')], max_length=20)),
                ('urutan', models.IntegerField(default=1)),
                ('pertanyaan', models.TextField()),
                ('opsi_a', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_b', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_d', models.CharField(blank=True, max_length=255, null=True)),
                ('jawaban_drag', models.JSONField(blank=True, null=True)),
                ('jawaban_isian', models.JSONField(blank=True, null=True)),
                ('jawaban_benarsalah', models.BooleanField(blank=True, null=True)),
                ('jawaban_benar', models.CharField(blank=True, max_length=10, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='quiz.quiz')),
            ],
        ),
    ]
