# Generated by Django 5.2.7 on 2025-11-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_soal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='jawaban_benar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
