# Generated by Django 5.2.7 on 2025-11-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_soal_jawaban_benar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('xp_minimal', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='soal',
            name='penjelasan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soal',
            name='poin',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ProgressQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_benar', models.IntegerField(default=0)),
                ('total_salah', models.IntegerField(default=0)),
                ('xp_total', models.IntegerField(default=0)),
                ('selesai', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_user', models.TextField()),
                ('benar', models.BooleanField(default=False)),
                ('xp_didapat', models.IntegerField(default=0)),
                ('poin_didapat', models.IntegerField(default=0)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.soal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
