# Generated by Django 5.2.7 on 2025-11-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_riwayatkuis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riwayatkuis',
            old_name='skor_tertinggi',
            new_name='skor',
        ),
    ]
