# Generated by Django 5.2.7 on 2025-12-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_skor_tertinggi_riwayatkuis_skor'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatkuis',
            name='best_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
