# Generated by Django 5.2.7 on 2025-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_score_userprofile_total_poin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='waktu_terbaik',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_xp',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank_name',
            field=models.CharField(default='Pemula tanda baca', max_length=100),
        ),
    ]
