# Generated by Django 5.2.7 on 2025-12-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_waktu_terbaik_alter_userprofile_max_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='waktu_terbaik',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='best_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
