# Generated by Django 5.2.7 on 2025-12-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_waktu_terbaik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='best_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
