# Generated by Django 5.2.7 on 2025-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_best_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='best_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
