# Generated by Django 5.2.7 on 2025-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_best_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_time_spent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
