# Generated by Django 5.2.7 on 2025-12-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_total_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_time_spent',
            field=models.FloatField(default=0),
        ),
    ]
