# Generated by Django 5.2.7 on 2025-12-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_total_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
