# Generated by Django 5.2.7 on 2025-12-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
