# Generated by Django 5.2.7 on 2025-12-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_leaderboard_total_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
